### ISSUE TITLE
AttributeError: module 'diffvg' has no attribute 'ShapeType'

### ISSUE THREAD

**Issue by mrunalsen** [ximinng/SVGDreamer#13]
![gitissue](https://github.com/ximinng/SVGDreamer/assets/97331976/46549459-8c66-4d3d-baed-4b2975807449)
I keep getting this issue (running on google colab)

**Comment by ximinng** [comment]
Hi, mrunalsen?

Looks like an environmental problem. Was diffvg successfully installed?
