### ISSUE TITLE
Operating systems supported by the project

### ISSUE THREAD

**Issue by asdj123d** [ximinng/SVGDreamer#15]
I'd like to ask if the only operating system supported by this program is linux.

**Comment by ximinng** [comment]
to be honest, I only build and run this project on ubuntu. And you maybe face bugs when you run on other platforms.

**Comment by LeeTaylorLondon** [comment]
Traceback (most recent call last):
  File "C:\Users\lees_\PycharmProjects\SVG_Render\SVGDreamer\svgdreamer.py", line 17, in <module>
    from svgdreamer.pipelines.SVGDreamer_pipeline import SVGDreamerPipeline
  File "C:\Users\lees_\PycharmProjects\SVG_Render\SVGDreamer\svgdreamer\pipelines\SVGDreamer_pipeline.py", line 23, in <module>
    from svgdreamer.painter import (CompPainter, CompPainterOptimizer, xing_loss_fn, Painter, PainterOptimizer,
  File "C:\Users\lees_\PycharmProjects\SVG_Render\SVGDreamer\svgdreamer\painter\__init__.py", line 5, in <module>
    from .painter_params import (
  File "C:\Users\lees_\PycharmProjects\SVG_Render\SVGDreamer\svgdreamer\painter\painter_params.py", line 15, in <module>
    import pydiffvg
ModuleNotFoundError: No module named 'pydiffvg'

---


How do I fix this? :(

**Comment by asdj123d** [comment]
This error means that your python environment has not successfully installed pydiffvg. If you want to reproduce this project, you'd better make sure that your computer is a linux system first, because some python libraries are only available in linux versions.
&nbsp;


请叫我老pai
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月31日(星期三) 上午9:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ximinng/SVGDreamer] Operating systems supported by the project (Issue #15)














 
Traceback (most recent call last):
 File "C:\Users\lees_\PycharmProjects\SVG_Render\SVGDreamer\svgdreamer.py", line 17, in 
 from svgdreamer.pipelines.SVGDreamer_pipeline import SVGDreamerPipeline
 File "C:\Users\lees_\PycharmProjects\SVG_Render\SVGDreamer\svgdreamer\pipelines\SVGDreamer_pipeline.py", line 23, in 
 from svgdreamer.painter import (CompPainter, CompPainterOptimizer, xing_loss_fn, Painter, PainterOptimizer,
 File "C:\Users\lees_\PycharmProjects\SVG_Render\SVGDreamer\svgdreamer\painter_init_.py", line 5, in 
 from .painter_params import (
 File "C:\Users\lees_\PycharmProjects\SVG_Render\SVGDreamer\svgdreamer\painter\painter_params.py", line 15, in 
 import pydiffvg
 ModuleNotFoundError: No module named 'pydiffvg'
 
 
How do I fix this? :(

**Comment by LeeTaylorLondon** [comment]
okay i am installing ubuntu-desktop through wsl and everything else necessary, if i follow the same instructions but inside of ubuntu-desktop it should work?

**Comment by asdj123d** [comment]
Of course, if your computer has a gpu graphics card, everything is fine.


请叫我老pai
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ximinng/SVGDreamer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月1日(星期四) 上午8:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ximinng/SVGDreamer] Operating systems supported by the project (Issue #15)





 
okay i am installing ubuntu-desktop through wsl and everything else necessary, if i follow the same instructions but inside of ubuntu-desktop it should work?

**Comment by LeeTaylorLondon** [comment]
hi i am on linux ubuntu 20.04 i did the docker install thing and this is what i got:

Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy' nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object no such file or directory: unknown.

**Comment by ximinng** [comment]
> hi i am on linux ubuntu 20.04 i did the docker install thing and this is what i got:
> 
> Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy' nvidia-container-cli: initialization error: load library failed: libnvidia-ml.so.1: cannot open shared object no such file or directory: unknown.

Hi, I don't have that problem.
I think it may be because docker does not support Nvidia, can you confirm that your docker supports GPU calls?

**Comment by LeeTaylorLondon** [comment]
hi i was using linux ubuntu 20.04 on windows 11, i am now using LTS ubuntu linux 24.04, it seems when i run the docker image or install shell script, i am missing a lot of requirements before it, like cmake, nvidia gpu stuff, and other things :( is there a list of things i need to do my linux install before running the install.sh or running the docker image ?? sorry for all the messages i am dying trying to get this installed

**Comment by ximinng** [comment]
> hi i was using linux ubuntu 20.04 on windows 11, i am now using LTS ubuntu linux 24.04, it seems when i run the docker image or install shell script, i am missing a lot of requirements before it, like cmake, nvidia gpu stuff, and other things :( is there a list of things i need to do my linux install before running the install.sh or running the docker image ?? sorry for all the messages i am dying trying to get this installed

I understand how you feel, and I want to help you. But I need more information.
For example, what happens when you run install.sh?
Can you give me some screenshots or error messages?
