### ISSUE TITLE
"precision" not defined, VPSD_pipeline

### ISSUE THREAD

**Issue by jacerniello** [ximinng/SVGDreamer#16]
Hi there, first of all, the work you've done is amazing, and thank you for making the code public.

Issue: it appears that the variable "precision" is not defined in the file [VPSD_pipeline.py](https://github.com/ximinng/SVGDreamer/blob/main/svgdreamer/painter/VPSD_pipeline.py), line 32. I see a commit was made 3 months ago (to add fp16 support), and there's of course a reference in config.yaml, but I don't think it's reading from there correctly.

Could you fix this when you get a chance?

Edit: Actually I think all that needs to be done is rename "precision" to "dtype"

**Comment by ximinng** [comment]
Sorry, because of my negligence, caused this problem, I have fixed.
Thanks for asking this question~

**Comment by jacerniello** [comment]
All good, thank you!
