### ISSUE TITLE
cudaErrorInvalidDevice

### ISSUE THREAD

**Issue by davidaknowles** [ximinng/SVGDreamer#19]
Hi - the script successfully runs SD/DDPM but then hits an error: 
```
pydiffvg/render_pytorch.py", line 692, in backward diffvg.render(scene,
RuntimeError: radix_sort: failed on 1st step: cudaErrorInvalidDevice: invalid device ordinal
```
Any ideas? This is on Ubuntu 24. torch finds the GPU fine (obviously because SD wouldn't run otherwise).

**Comment by ximinng** [comment]
Sorry, I have not encountered this problem.
I think there are two possibilities: 1.diffvg is not installed correctly. 2. Test if pytorch can call the GPU correctly.
