### ISSUE TITLE
Trouble running through the examples

### ISSUE THREAD

**Issue by xkahn** [ximinng/SVGDreamer#3]
I'm having some trouble trying some of the samples. Here are the steps I took:

I installed created a conda environment with python 3.8 called "svgdreamer" and installed diffvg.git

I installed the pip packages: `transformers`, `diffusers`, `opencv-python`, `shapely`, `hydra-core`, `scikit-image`, `torchvision`, `tqdm`, `matplotlib`

But I'm getting errors on:

`ModuleNotFoundError: No module named 'clip'` in `SVGDreamer/ImageReward/models/AestheticScore.py` and 

`ModuleNotFoundError: No module named 'svgdreamer.svgtools.tff'` in `SVGDreamer/svgdreamer/svgtools/__init__.py`

It doesn't appear that `'svgdreamer.svgtools.tff'` is used yet, so I was able to get further by commenting that out, but `clip` looks important and not related to https://pypi.org/project/clip/

**Comment by ximinng** [comment]
Hello xkahn,

You can follow the steps below to quickly get up and running with SVGDreamer.
These steps will let you run quick inference locally.

In the top level directory run,

```bash
sh script/install.sh
```

or using docker images,

```shell
docker run --name svgdreamer --gpus all -it --ipc=host ximingxing/svgrender:v1 /bin/bash
```

best regards,
ximing

**Comment by wshjtuk** [comment]
I met the same problem, and I followed the steps to run the shell file but also failed to run.

**Comment by 578578wu** [comment]
First of all thank you very much for this great job.
But I still don’t have the pydiffvg library after running "sh script/install.sh",
show"ERROR: Could not find a version that satisfies the requirement pydiffvg (from versions: none)
ERROR: No matching distribution found for pydiffvg"

**Comment by 578578wu** [comment]
I have solved the previous problem. Thank you, but this problem still occurs. 
 File "/root/SVGDreamer-main/diffvg/pydiffvg/render_pytorch.py", line 28, in RenderFunction
    filter = pydiffvg.PixelFilter(type = diffvg.FilterType.box,
AttributeError: module 'diffvg' has no attribute 'FilterType'

**Comment by 578578wu** [comment]
> 我在尝试某些示例时遇到了一些问题。以下是我采取的步骤：
> 
> 我安装了一个名为“svgdreamer”的 python 3.8 创建的 conda 环境并安装了 diffvg.git
> 
> 我安装了 pip 软件包：`transformers`, `diffusers`, `opencv-python`, `shapely`, `hydra-core`, `scikit-image`, `torchvision`, `tqdm`,`matplotlib`
> 
> 但我收到错误：
> 
> `ModuleNotFoundError: No module named 'clip'`在`SVGDreamer/ImageReward/models/AestheticScore.py`和
> 
> `ModuleNotFoundError: No module named 'svgdreamer.svgtools.tff'`在`SVGDreamer/svgdreamer/svgtools/__init__.py`
> 
> 它似乎`'svgdreamer.svgtools.tff'`还没有被使用，所以我能够通过注释掉它来进一步了解，但看起来很重要并且与https://pypi.org/project/clip/`clip`无关[](https://pypi.org/project/clip/)

Will you encounter the lack of pre-trained models?

**Comment by ximinng** [comment]
download pretrained models by setting 'diffuser.download=True' in the `/conf/config.yaml`.
