### ISSUE TITLE
approximate gpu usage

### ISSUE THREAD

**Issue by CodeGeek04** [ximinng/SVGDreamer#6]
I tried running the code locally on my machine. I tried all different models available (for sd), but turns out my VRAM is not enought to test these. Can the authors maybe give few approximations for the resources required, or even share their system specifications used to train/inference the model.

**Comment by ximinng** [comment]
Hello CodeGeek04,

To run the examples in the README, you need a Nvidia V100 GPU with 30GB of VRAM. But if you're not satisfied, you can set `vpsd.n_particle=1`, `vpsd.vsd_n_particle=1` and `phi_n_particle=1`
