### ISSUE TITLE
推理速度问题

### ISSUE THREAD

**Issue by fh1999** [ximinng/SVGDreamer#7]
感谢你的工作～我在跑样例的时候发现 1000步优化，耗时超过一个小时，我使用的是V100 32G 显卡，请问这个速度是否正常，是否有办法提速？

**Comment by fh1999** [comment]
跑完了，总耗时4个小时

**Comment by ximinng** [comment]
Dear fh1999,

If you don't have a more powerful GPU available, I highly recommend turning on **xformer** (make sure it turns on successfully, as explained in the log).
In addition, the default run script synthesizes 6 SVG at once, you can reduce the number of syntheses to speed up.
(For instance, you can set `vpsd.n_particle=1`, `vpsd.vsd_n_particle=1` and `vpsd.phi_n_particle=1`)
Although the default is 1000 steps optimization, many times it does not take this long, please query the intermediate results in the existing results directory.

Best Regards,
ximing

**Comment by ximinng** [comment]
In the expansion of SVGDreamer, we added vector glyphs. Vector posters are implemented by placing the vector font on top of the canvas (on top of the content).
Given a word string `$\mathcal{W}$ with $n$ letters $\{l_1, \dots, l_n\}$`, our method is applied to all letters, generating glyphs that matches the poster theme through text prompts.
First, we define the glyph input. It consists of a transformable portion, which includes **color, layout transform, angle, and letter spacing**, and a non-transformable portion, which includes **words, font, font size, alignment, and capitalization.**

**Comment by wh920** [comment]
> In the expansion of SVGDreamer, we added vector glyphs. Vector posters are implemented by placing the vector font on top of the canvas (on top of the content). Given a word string `$\mathcal{W}$ with $n$ letters $\{l_1, \dots, l_n\}$`, our method is applied to all letters, generating glyphs that matches the poster theme through text prompts. First, we define the glyph input. It consists of a transformable portion, which includes **color, layout transform, angle, and letter spacing**, and a non-transformable portion, which includes **words, font, font size, alignment, and capitalization.**

Hi Ximing! Thanks for your amazing work. I just get started in your repo. I'm particularly curious about the possibility of generating poster with SVGDreamer. Would you mind elaborating more on how to reproduce it? For example, what's the script to generate it? And how to define the glyph input in files? Thank you!

**Comment by ximinng** [comment]
> > In the expansion of SVGDreamer, we added vector glyphs. Vector posters are implemented by placing the vector font on top of the canvas (on top of the content). Given a word string `$\mathcal{W}$ with $n$ letters $\{l_1, \dots, l_n\}$`, our method is applied to all letters, generating glyphs that matches the poster theme through text prompts. First, we define the glyph input. It consists of a transformable portion, which includes **color, layout transform, angle, and letter spacing**, and a non-transformable portion, which includes **words, font, font size, alignment, and capitalization.**
> 
> Hi Ximing! Thanks for your amazing work. I just get started in your repo. I'm particularly curious about the possibility of generating poster with SVGDreamer. Would you mind elaborating more on how to reproduce it? For example, what's the script to generate it? And how to define the glyph input in files? Thank you!

Thanks for your attention, generating vector posters is an extension of svgdreamer, so it is not in this repository.
But given the many people interested, I will recently open source svgdreamer's workflow for creating vector posters.

**Comment by wh920** [comment]
> > > In the expansion of SVGDreamer, we added vector glyphs. Vector posters are implemented by placing the vector font on top of the canvas (on top of the content). Given a word string `$\mathcal{W}$ with $n$ letters $\{l_1, \dots, l_n\}$`, our method is applied to all letters, generating glyphs that matches the poster theme through text prompts. First, we define the glyph input. It consists of a transformable portion, which includes **color, layout transform, angle, and letter spacing**, and a non-transformable portion, which includes **words, font, font size, alignment, and capitalization.**
> > 
> > 
> > Hi Ximing! Thanks for your amazing work. I just get started in your repo. I'm particularly curious about the possibility of generating poster with SVGDreamer. Would you mind elaborating more on how to reproduce it? For example, what's the script to generate it? And how to define the glyph input in files? Thank you!
> 
> Thanks for your attention, generating vector posters is an extension of svgdreamer, so it is not in this repository. But given the many people interested, I will recently open source svgdreamer's workflow for creating vector posters.

Sounds great! Looking forward to giving it a try when it's ready.
