### ISSUE TITLE
Downloading diffusion model

### ISSUE THREAD

**Issue by wshjtuk** [ximinng/SVGDreamer#8]
I wonder how to download the diffusion model by using wget or what is the link of the model, furthermore, what dir to put the model? Due to there is no proxy in the dev machine, I have to download it in PC and upload it to the dev machine.

Thank you.

**Comment by ximinng** [comment]
Dear wshjtuk,

Please note that the Stable Diffusion Model is downloaded from huggingface by **diffusers**.
But you can still download it manually~
Model Link: `https://huggingface.co/stabilityai/stable-diffusion-2-1-base`
Default model is stored in the `/home/user/.cache/huggingface/hub/models--stabilityai--stable-diffusion-2-1-base`.

Best Regards，
ximing
