### ISSUE TITLE
Running Docker Image

### ISSUE THREAD

**Issue by bamsom** [ximinng/SVGDreamer#9]
An interesting work! 

I am trying the sample scripts inside the docker container and keep getting errors like:
'... ModuleNotFoundError: No module named 'hydra' ...'
I pip installed some packages but not sure I am doing it right.  I have never succeeded in installing diffvg locally, and I was hoping the docker image comes all preinstalled.  

What am I doing wrong?  I have the same issue with DiffSketcher repo.

**Comment by bamsom** [comment]
Btw, I am on a ubuntu machine with RTX 4090.  CUDA 11.3 suport for the GPU might be an issue?

**Comment by ximinng** [comment]
You can try the docker image we provide,

```bash
docker run --name svgdreamer --gpus all -it --ipc=host ximingxing/svgrender:v1 /bin/bash
```

In addition, the installation of diffvg requires the gcc version, which may be the reason why you cannot install successfully.
